// tauri-plugin-screen-capture 构建脚本
//
// - COMMANDS 固定为 3 条命令面（capture_start / capture_stop / capture_status），
//   供 tauri-plugin build crate 自动生成 permissions/autogenerated/ 与 ACL schema。
// - android_path("android")：android 目标构建时向 tauri CLI 导出本插件安卓工程
//   路径（cargo:android_library_path），由 CLI 再生成 gen/android/tauri.settings.gradle
//   的 include（hg-guard 同模式先例）。
// - 前台服务块（mediaProjection 类型）放本插件 android/src/main/AndroidManifest.xml，
//   由 gradle manifest merger 自动并入宿主 App，不改 App 主 Manifest。

const COMMANDS: &[&str] = &["capture_start", "capture_stop", "capture_status"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
