// tauri-plugin-hg-guard 构建脚本
//
// - COMMANDS 固定为 6 条命令面（阶段 2a 契约，供 tauri-plugin build crate
//   自动生成 permissions/autogenerated/allow-*.toml 与 ACL schema）。
// - android_path("android")：android 目标构建时向 tauri CLI 导出本插件
//   安卓工程路径（cargo:android_library_path），由 CLI 再生成
//   gen/android/tauri.settings.gradle / tauri.build.gradle.kts 的 include。
// - Guard 的 service 块不走 update_android_manifest（那是往 App 主 Manifest
//   手插块的机制），而是放本插件 android/src/main/AndroidManifest.xml，由
//   gradle manifest merger 自动并入（NFC 块同仓先例之外的标准插件机制）。

const COMMANDS: &[&str] = &[
    "hg_status",
    "hg_connect",
    "hg_disconnect",
    "hg_prepare_vpn",
    "hg_control_start",
    "hg_control_stop",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
