plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

// tauri-plugin-screen-capture 安卓 module：
// - :tauri-android 由宿主 App 的 gen/android/tauri.settings.gradle 提供
//   （AUTOGENERATED，tauri CLI 按插件构建元数据再生成 include）。
// - namespace 取 dev.huanvae.screen.capture.tauri：仅承载插件适配类
//   （R/Manifest 解析）；采集服务在 dev.huanvae.screen.capture 包。

android {
    namespace = "dev.huanvae.screen.capture.tauri"
    compileSdk = 36

    defaultConfig {
        minSdk = 28
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation(project(":tauri-android"))
    // @ActivityCallback 回调签名用 androidx.activity.result.ActivityResult；
    // tauri-android 以 implementation 依赖它，不外暴露，这里显式声明（版本对齐宿主 app module）。
    implementation("androidx.activity:activity-ktx:1.10.1")
}
